# full_names = db.Column(db.String(50), unique=True, nullable=True)
# phone_number = db.Column(db.Integer, unique=True, nullable=True)
# gender = db.Column(db.String(20))
# personal_summary = db.Column(db.Text(), unique=True, nullable=True)
# education = db.Column(db.Text(), unique=True, nullable=True)
# work_experience = db.Column(db.Text(), unique=True, nullable=True)
# projects = db.Column(db.Text())
# accomplishment = db.Column(db.Text(), unique=True, nullable=True)
# referees = db.Column(db.Text(), unique=True, nullable=True)
# image = db.Column(db.String(20))
# linked_in_link = db.Column(db.String(100))
# twitter_link = db.Column(db.String(100))
# fb_link = db.Column(db.String(100))